using AutoMapper;
using Microsoft.AspNetCore.Http;
using SeeSayMicroservices.Models.Dto;

namespace SeeSayMicroservices.Services.MapperProfiles;

public class TicketProfile : Profile
{
    public TicketProfile()
    {
        CreateMap<IFormCollection, TicketDto>()
            .ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src["UserId"]))
            .ForMember(dest => dest.PostId, opt => opt.MapFrom(src => int.Parse(src["PostId"])))
            .ForMember(dest => dest.SignalConnectionId,
                opt => opt.MapFrom(src => src["SignalConnectionId"]))
            .ForMember(dest => dest.ShouldAutoGenerateDescription,
                opt => opt.MapFrom(src => bool.Parse(src["ShouldAutoGenerateDescription"])));
    }
}