#nullable enable
namespace SeeSayMicroservices.Models.Dto;

public class TicketDto
{
    public string UserId { get; set; } = null!;
    public string SignalConnectionId { get; set; } = null!;
    public int PostId { get; set; }
    public bool ShouldAutoGenerateDescription { get; set; }
    public string ImageUrl { get; set; } = null!;
}